<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PayrollItem extends Model
{
    protected $fillable = [
        'payroll_id',
        'employee_id',
        'currency_mode',

        // Legacy / Combined
        'basic_salary',
        'housing_allowance',
        'transport_allowance',
        'communication_allowance',
        'education_allowance',
        'leave_allowance',
        'bonus',
        'overtime',
        'other_earnings',
        'other_earnings_desc',
        'school_top_up',
        'gross_pay',

        // Dual USD / ZWG Earnings
        'basic_salary_usd',
        'basic_salary_zwg',
        'allowances_usd',
        'allowances_zwg',
        'bonus_usd',
        'bonus_zwg',
        'overtime_usd',
        'overtime_zwg',
        'gross_usd',
        'gross_zwg',

        // Legacy / Combined Deductions
        'paye',
        'aids_levy',
        'nssa_employee',
        'nssa_employer',
        'trade_union',
        'nec',
        'loan_repayment',
        'other_deductions',
        'other_deductions_desc',
        'total_deductions',
        'net_pay',

        // Dual USD / ZWG Deductions & Tax Credits
        'paye_usd',
        'paye_zwg',
        'aids_levy_usd',
        'aids_levy_zwg',
        'nssa_employee_usd',
        'nssa_employee_zwg',
        'nssa_employer_usd',
        'nssa_employer_zwg',
        'nec_employee_usd',
        'nec_employee_zwg',
        'nec_employer_usd',
        'nec_employer_zwg',
        'trade_union_usd',
        'trade_union_zwg',
        'medical_aid_usd',
        'medical_aid_zwg',
        'medical_aid_tax_credit_usd',
        'medical_aid_tax_credit_zwg',
        'loan_repayment_usd',
        'loan_repayment_zwg',
        'other_deductions_usd',
        'other_deductions_zwg',
        'total_deductions_usd',
        'total_deductions_zwg',
        'net_pay_usd',
        'net_pay_zwg',

        'payment_method',
        'bank_account',
        'status',
        'notes',
        'leave_days_accrued',
        'leave_days_taken',
        'leave_balance',
    ];

    protected $casts = [
        'basic_salary' => 'decimal:2',
        'housing_allowance' => 'decimal:2',
        'transport_allowance' => 'decimal:2',
        'communication_allowance' => 'decimal:2',
        'education_allowance' => 'decimal:2',
        'leave_allowance' => 'decimal:2',
        'bonus' => 'decimal:2',
        'overtime' => 'decimal:2',
        'other_earnings' => 'decimal:2',
        'school_top_up' => 'decimal:2',
        'gross_pay' => 'decimal:2',

        'basic_salary_usd' => 'decimal:2',
        'basic_salary_zwg' => 'decimal:2',
        'allowances_usd' => 'decimal:2',
        'allowances_zwg' => 'decimal:2',
        'bonus_usd' => 'decimal:2',
        'bonus_zwg' => 'decimal:2',
        'overtime_usd' => 'decimal:2',
        'overtime_zwg' => 'decimal:2',
        'gross_usd' => 'decimal:2',
        'gross_zwg' => 'decimal:2',

        'paye' => 'decimal:2',
        'aids_levy' => 'decimal:2',
        'nssa_employee' => 'decimal:2',
        'nssa_employer' => 'decimal:2',
        'trade_union' => 'decimal:2',
        'nec' => 'decimal:2',
        'loan_repayment' => 'decimal:2',
        'other_deductions' => 'decimal:2',
        'total_deductions' => 'decimal:2',
        'net_pay' => 'decimal:2',

        'paye_usd' => 'decimal:2',
        'paye_zwg' => 'decimal:2',
        'aids_levy_usd' => 'decimal:2',
        'aids_levy_zwg' => 'decimal:2',
        'nssa_employee_usd' => 'decimal:2',
        'nssa_employee_zwg' => 'decimal:2',
        'nssa_employer_usd' => 'decimal:2',
        'nssa_employer_zwg' => 'decimal:2',
        'nec_employee_usd' => 'decimal:2',
        'nec_employee_zwg' => 'decimal:2',
        'nec_employer_usd' => 'decimal:2',
        'nec_employer_zwg' => 'decimal:2',
        'trade_union_usd' => 'decimal:2',
        'trade_union_zwg' => 'decimal:2',
        'medical_aid_usd' => 'decimal:2',
        'medical_aid_zwg' => 'decimal:2',
        'medical_aid_tax_credit_usd' => 'decimal:2',
        'medical_aid_tax_credit_zwg' => 'decimal:2',
        'loan_repayment_usd' => 'decimal:2',
        'loan_repayment_zwg' => 'decimal:2',
        'other_deductions_usd' => 'decimal:2',
        'other_deductions_zwg' => 'decimal:2',
        'total_deductions_usd' => 'decimal:2',
        'total_deductions_zwg' => 'decimal:2',
        'net_pay_usd' => 'decimal:2',
        'net_pay_zwg' => 'decimal:2',
        'leave_days_accrued' => 'decimal:2',
        'leave_days_taken' => 'decimal:2',
        'leave_balance' => 'decimal:2',
    ];

    public function payroll(): BelongsTo { return $this->belongsTo(Payroll::class); }
    public function employee(): BelongsTo { return $this->belongsTo(Employee::class); }
}
